# Generated by Django 4.0.6 on 2022-09-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('youtube_link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='MbtiLecture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('E', models.IntegerField()),
                ('I', models.IntegerField()),
                ('S', models.IntegerField()),
                ('N', models.IntegerField()),
                ('T', models.IntegerField()),
                ('F', models.IntegerField()),
                ('P', models.IntegerField()),
                ('J', models.IntegerField()),
                ('lecture_id', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='main.lectures')),
            ],
        ),
    ]
