# Generated by Django 4.0.6 on 2022-09-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtilecture',
            old_name='E',
            new_name='E_I',
        ),
        migrations.RenameField(
            model_name='mbtilecture',
            old_name='F',
            new_name='P_J',
        ),
        migrations.RenameField(
            model_name='mbtilecture',
            old_name='I',
            new_name='S_N',
        ),
        migrations.RenameField(
            model_name='mbtilecture',
            old_name='J',
            new_name='T_F',
        ),
        migrations.RemoveField(
            model_name='mbtilecture',
            name='N',
        ),
        migrations.RemoveField(
            model_name='mbtilecture',
            name='P',
        ),
        migrations.RemoveField(
            model_name='mbtilecture',
            name='S',
        ),
        migrations.RemoveField(
            model_name='mbtilecture',
            name='T',
        ),
    ]
